version: '3.7'

services:
  database_medcloud:
    image: postgres
    container_name: med_cloud
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=med
      - POSTGRES_PASSWORD=cloud   
      - POSTGRES_DB=medcloud  
    volumes:
      - ./pgdata:/data/postgres